version: '3.3'

services:
  database:
    container_name: database
    image: postgres:15.2-alpine
    env_file: .env
    volumes:
      - .:/var/lib/postgresql/data
      - ./application/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - database
#    ports:
#      - "3000:3000"
    volumes:
      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"


#volumes:
#  gem_cache:
#  node_modules:

