pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building application..'
                sh 'docker build -t frelaxy/app:latest -f docker/app/Dockerfile .'
                echo 'Building database..'
                sh 'docker build -t frelaxy/database:latest -f docker/database/Dockerfile .'
                echo 'Building nginx..'
                sh 'docker build -t frelaxy/nginx:latest -f docker/nginx/Dockerfile .'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'docker-compose up -d'
            }
        }
        stage('Push images to repository..') {
            steps {
                echo 'Pushing images to repository..'
                sh 'docker login -u frelaxy -p dckr_pat_d2gz5rL_xn5rV2cVUEIUO8mdXng'
                sh 'docker push frelaxy/app:latest'
                sh 'docker push frelaxy/database:latest'
                sh 'docker push frelaxy/nginx:latest'
            }
        }
        stage('Delete pipline artifacts..') {
            steps {
                echo 'Deleting images...'
                sh 'docker-compose down'
                sh 'docker rmi frelaxy/app:latest frelaxy/database:latest frelaxy/nginx:latest'
            }
        }
    }
}