apiVersion: v1

kind: Secret

metadata:
  name: secrets

type: Opaque

stringData:
  DATABASE_HOST: postgres-service
  POSTGRES_DB: questions_and_answers
  POSTGRES_USER: kiryl
  POSTGRES_PASSWORD: '1111'